2024-02-10 11:12:29,239 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-10 11:12:29,239 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Configure stats pid to 59462
2024-02-10 11:12:29,239 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/.config/wandb/settings
2024-02-10 11:12:29,239 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/settings
2024-02-10 11:12:29,239 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-10 11:12:29,239 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-10 11:12:29,239 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-10 11:12:29,240 INFO    MainThread:59462 [wandb_init.py:_log_setup():526] Logging user logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_111229-kclksitw/logs/debug.log
2024-02-10 11:12:29,240 INFO    MainThread:59462 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_111229-kclksitw/logs/debug-internal.log
2024-02-10 11:12:29,240 INFO    MainThread:59462 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc8e01641f0>
2024-02-10 11:12:29,240 INFO    MainThread:59462 [wandb_init.py:init():566] calling init triggers
2024-02-10 11:12:29,240 INFO    MainThread:59462 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-10 11:12:29,240 INFO    MainThread:59462 [wandb_init.py:init():591] re-initializing run, found existing run on stack: xyol6w2n
2024-02-10 11:12:29,242 INFO    MainThread:59462 [wandb_run.py:_finish():1962] finishing run aipi549/aipi540/xyol6w2n
2024-02-10 11:12:29,243 INFO    MainThread:59462 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-02-10 11:12:29,244 INFO    MainThread:59462 [wandb_run.py:_restore():2185] restore
2024-02-10 11:12:29,244 INFO    MainThread:59462 [wandb_run.py:_restore():2191] restore done
2024-02-10 11:12:32,087 INFO    MainThread:59462 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-02-10 11:12:32,087 INFO    MainThread:59462 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-02-10 11:12:32,093 INFO    MainThread:59462 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-02-10 11:12:32,164 INFO    MainThread:59462 [wandb_init.py:init():616] starting backend
2024-02-10 11:12:32,164 INFO    MainThread:59462 [wandb_init.py:init():620] setting up manager
2024-02-10 11:12:32,167 INFO    MainThread:59462 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-02-10 11:12:32,168 INFO    MainThread:59462 [wandb_init.py:init():628] backend started and connected
2024-02-10 11:12:32,194 INFO    MainThread:59462 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-02-10 11:12:32,194 INFO    MainThread:59462 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-10 11:12:32,194 INFO    MainThread:59462 [wandb_init.py:init():720] updated telemetry
2024-02-10 11:12:32,343 INFO    MainThread:59462 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-10 11:12:33,697 INFO    MainThread:59462 [wandb_run.py:_on_init():2254] communicating current version
2024-02-10 11:12:34,151 INFO    MainThread:59462 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.16.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-02-10 11:12:34,151 INFO    MainThread:59462 [wandb_init.py:init():804] starting run threads in backend
2024-02-10 11:12:38,307 WARNING MainThread:59462 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 817, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-02-10 11:12:39,656 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Configure stats pid to 59462
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/.config/wandb/settings
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/settings
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_init.py:_log_setup():526] Logging user logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_111239-kk1bv7hh/logs/debug.log
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_111239-kk1bv7hh/logs/debug-internal.log
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_init.py:init():566] calling init triggers
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_init.py:init():616] starting backend
2024-02-10 11:12:39,657 INFO    MainThread:59462 [wandb_init.py:init():620] setting up manager
2024-02-10 11:12:39,658 INFO    MainThread:59462 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-02-10 11:12:39,659 INFO    MainThread:59462 [wandb_init.py:init():628] backend started and connected
2024-02-10 11:12:39,674 INFO    MainThread:59462 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-02-10 11:12:39,674 INFO    MainThread:59462 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-10 11:12:39,674 INFO    MainThread:59462 [wandb_init.py:init():720] updated telemetry
2024-02-10 11:12:39,717 INFO    MainThread:59462 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-10 11:13:28,038 WARNING MainThread:59462 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-02-10 11:13:29,247 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-10 11:13:29,247 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Configure stats pid to 59462
2024-02-10 11:13:29,247 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/.config/wandb/settings
2024-02-10 11:13:29,247 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/settings
2024-02-10 11:13:29,247 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-10 11:13:29,247 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-10 11:13:29,247 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-10 11:13:29,247 INFO    MainThread:59462 [wandb_init.py:_log_setup():526] Logging user logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_111329-64emolsk/logs/debug.log
2024-02-10 11:13:29,248 INFO    MainThread:59462 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_111329-64emolsk/logs/debug-internal.log
2024-02-10 11:13:29,248 INFO    MainThread:59462 [wandb_init.py:init():566] calling init triggers
2024-02-10 11:13:29,248 INFO    MainThread:59462 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-10 11:13:29,248 INFO    MainThread:59462 [wandb_init.py:init():616] starting backend
2024-02-10 11:13:29,248 INFO    MainThread:59462 [wandb_init.py:init():620] setting up manager
2024-02-10 11:13:29,249 INFO    MainThread:59462 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-02-10 11:13:29,250 INFO    MainThread:59462 [wandb_init.py:init():628] backend started and connected
2024-02-10 11:13:29,263 INFO    MainThread:59462 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-02-10 11:13:29,263 INFO    MainThread:59462 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-10 11:13:29,263 INFO    MainThread:59462 [wandb_init.py:init():720] updated telemetry
2024-02-10 11:13:29,301 INFO    MainThread:59462 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-10 11:13:34,990 WARNING MainThread:59462 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-02-10 11:14:46,255 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-10 11:14:46,256 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Configure stats pid to 59462
2024-02-10 11:14:46,256 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/.config/wandb/settings
2024-02-10 11:14:46,256 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/settings
2024-02-10 11:14:46,256 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-10 11:14:46,256 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-10 11:14:46,256 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-10 11:14:46,256 INFO    MainThread:59462 [wandb_init.py:_log_setup():526] Logging user logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_111446-j4iqub79/logs/debug.log
2024-02-10 11:14:46,256 INFO    MainThread:59462 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_111446-j4iqub79/logs/debug-internal.log
2024-02-10 11:14:46,256 INFO    MainThread:59462 [wandb_init.py:init():566] calling init triggers
2024-02-10 11:14:46,257 INFO    MainThread:59462 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-10 11:14:46,257 INFO    MainThread:59462 [wandb_init.py:init():616] starting backend
2024-02-10 11:14:46,257 INFO    MainThread:59462 [wandb_init.py:init():620] setting up manager
2024-02-10 11:14:46,258 INFO    MainThread:59462 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-02-10 11:14:46,259 INFO    MainThread:59462 [wandb_init.py:init():628] backend started and connected
2024-02-10 11:14:46,279 INFO    MainThread:59462 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-02-10 11:14:46,279 INFO    MainThread:59462 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-10 11:14:46,279 INFO    MainThread:59462 [wandb_init.py:init():720] updated telemetry
2024-02-10 11:14:46,356 INFO    MainThread:59462 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
