2024-02-04 16:36:09,307 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Configure stats pid to 24647
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/.config/wandb/settings
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/settings
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_init.py:_log_setup():526] Logging user logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/run-20240204_163609-70ygmbij/logs/debug.log
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/run-20240204_163609-70ygmbij/logs/debug-internal.log
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fef705a2040>
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_init.py:init():566] calling init triggers
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-04 16:36:09,308 INFO    MainThread:24647 [wandb_init.py:init():591] re-initializing run, found existing run on stack: bsqhdhmb
2024-02-04 16:36:09,311 INFO    MainThread:24647 [wandb_run.py:_finish():1962] finishing run aipi549/aipi540/bsqhdhmb
2024-02-04 16:36:09,311 INFO    MainThread:24647 [jupyter.py:save_history():445] not saving jupyter history
2024-02-04 16:36:09,311 INFO    MainThread:24647 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-04 16:36:09,311 INFO    MainThread:24647 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-04 16:36:09,507 ERROR   MainThread:24647 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 601, in init
    latest_run.finish()
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1953, in finish
    return self._finish(exit_code, quiet)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1981, in _finish
    manager._inform_finish(run_id=self._run_id)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 218, in _inform_finish
    svc_iface._svc_inform_finish(run_id=run_id)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 56, in _svc_inform_finish
    self._sock_client.send(inform_finish=inform_finish)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-02-04 16:37:16,913 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Configure stats pid to 24647
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/.config/wandb/settings
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/settings
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_init.py:_log_setup():526] Logging user logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/run-20240204_163716-ul29n0pc/logs/debug.log
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/run-20240204_163716-ul29n0pc/logs/debug-internal.log
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fef92eb5040>
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_init.py:init():566] calling init triggers
2024-02-04 16:37:16,914 INFO    MainThread:24647 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-04 16:37:16,915 INFO    MainThread:24647 [wandb_init.py:init():616] starting backend
2024-02-04 16:37:16,915 INFO    MainThread:24647 [wandb_init.py:init():620] setting up manager
2024-02-04 16:37:16,987 ERROR   MainThread:24647 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-02-04 16:37:31,170 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Configure stats pid to 24647
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/.config/wandb/settings
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/settings
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_init.py:_log_setup():526] Logging user logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/run-20240204_163731-v1zdr1un/logs/debug.log
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/run-20240204_163731-v1zdr1un/logs/debug-internal.log
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_init.py:init():566] calling init triggers
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_init.py:init():616] starting backend
2024-02-04 16:37:31,171 INFO    MainThread:24647 [wandb_init.py:init():620] setting up manager
2024-02-04 16:37:31,364 ERROR   MainThread:24647 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-02-04 16:41:52,593 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-04 16:41:52,594 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Configure stats pid to 24647
2024-02-04 16:41:52,594 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/.config/wandb/settings
2024-02-04 16:41:52,594 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/settings
2024-02-04 16:41:52,594 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-04 16:41:52,594 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-04 16:41:52,594 INFO    MainThread:24647 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-04 16:41:52,594 INFO    MainThread:24647 [wandb_init.py:_log_setup():526] Logging user logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/run-20240204_164152-sg9igh1g/logs/debug.log
2024-02-04 16:41:52,595 INFO    MainThread:24647 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/wandb/run-20240204_164152-sg9igh1g/logs/debug-internal.log
2024-02-04 16:41:52,595 INFO    MainThread:24647 [wandb_init.py:init():566] calling init triggers
2024-02-04 16:41:52,595 INFO    MainThread:24647 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-04 16:41:52,595 INFO    MainThread:24647 [wandb_init.py:init():616] starting backend
2024-02-04 16:41:52,595 INFO    MainThread:24647 [wandb_init.py:init():620] setting up manager
